name: expression & contexts
on: [push, pull_request, issues, workflow_dispatch]
run-name: "Expression & contexts by @${{ gihub.actor }}, @${{ github.event_name }}"
jobs:
  using-expressions-and-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: expression
        id: expressions
        run: |
          echo "${{ 1 }}"
          echo "${{ 'this is a string' }}"
          echo "${{ null }}"
          echo "${{ true }}"
          echo "${{ 1 > 2 }}"
          echo "${{ 'string' == 'string' }}"
          echo "${{ true && false }}"
          echo "${{ true || (false && true) }}"

      - name: Dump contexts
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(jobs) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
